# Generated by Django 5.0.6 on 2024-07-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_persona_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='f_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='name',
            field=models.CharField(default='unnamed', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='number',
            field=models.CharField(default=123456789, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='rut',
            field=models.CharField(default=12345669, max_length=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
    ]
